### ISSUE TITLE
Future deprecated research.csc.fi references tracking

### ISSUE THREAD

**Issue by Nortamo** [CSCfi/csc-user-guide#137]
This issue exists to track links to research.csc.fi which become obsolete when the last of the software documentation for Taito is removed. 

**Needs consideration** (It depends where basic linux instructions should be found)

- [x] docs/computing/connecting.md:9:operating command line linux can be found for example from [here](https://research.csc.fi/csc-guide-linux-basics-for-csc). You can have several Puhti connections open in the same time.

**Links which will at some point be deprecated**

- [x] docs/data/Allas/using_allas/s3_client.md:74 https://research.csc.fi/pouta-install-client

- [x] docs/apps/geoconda.md:135:  [-X connection or NoMachine for Windows users]: https://research.csc.fi/csc-guide-connecting-the-servers-of-csc

- [x] docs/apps/geoconda.md:138:  [geo-env]: https://research.csc.fi/-/geo-env

- [x] docs/apps/geoconda.md:139:  [Python]: https://research.csc.fi/-/python

- [x] docs/apps/geoconda.md:141:  [Bioconda]: https://research.csc.fi/-/bioconda

- [x] docs/apps/lastools.md:31:    For now, Puhti does not support running __.exe__ files so if you need to install/run the closed source tools, use the Taito cluster. [Taito & LAStools documentation](https://research.csc.fi/-/lastools)

- [x] docs/apps/ipyrad.md:116:The maximum run time in Puhti is 14 days. In some cases running the ipyrad analysis step 3 may take even longer time. In those cases you can use the cPouta cloud service to set up your own virtual machine. Check [using-cpouta-for-biosciences](https://research.csc.fi/using-cpouta-for-biosciences) for more details.

**Bonus** (sui.csc.fi)

- [x] When sui goes down remove all references from `docs/accounts/index.md`

**Comment by Nortamo** [comment]
These seem to have been dealt with
